name: Android Build Release Workflow

on:
  push:
    branches:
      [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Release APK
        uses: ShowMeThe/github_action_release@v0.01
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
