name: Flix Fix Build Release Workflow

on:
  push:
    branches:
      [ master ]


jobs:
  apk:
    permissions:
      contents: write
    name: Generate and release APK
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Access TMDB_API_KEY
        env:
          TMDB_API_KEY: $
        run: echo TMDB_API_KEY=\"TMDB_API_KEY\" > ./local.properties
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: gradle
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build APK
        run: ./gradlew assembleRelease
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0.1
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/asset
          asset_name: Flix Fix.apk
          asset_content_type: application/vnd.android.package-archive
